### ISSUE TITLE
Use of magento2-plugin-visualization

### ISSUE THREAD

**Issue by vpietri** [magento-hackathon/magento2-plugin-visualization#3]
@KamilBalwierz  @steverobbins @avoelkl : I will publish a new release of my extension which will use magento2-plugin-visualization

[see commit](https://github.com/vpietri/magento2-developer-quickdevbar/commit/c3d5a339475660ce1083b9176bb3931c7ff022be/Block/Tab/Content/Plugin.php#L64-L76)

**Comment by vpietri** [comment]
I finally use ReflectionClass on PluginList instead of magento2-plugin-visualization

**Comment by LiamKarlMitchell** [comment]
composer require magento-hackaton/module-plugin-visualization:dev-master


  [InvalidArgumentException]
  Could not find a matching version of package magento-hackaton/module-plugin-visualization. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (st
  able).
